### ISSUE TITLE
Changing your version of r in rstudio to run phenotools

### ISSUE THREAD

**Issue by idaElken** [psychgen/phenotools#1]
On TSD on p697, my rstudio (in windows) was loaded with R version 3.4 so phenotools did not function. 

It might be helpful for others to know that:
If you need to update your version of R (to e.g. 4.0) in rstudio to run phenotools, please: Go to “Tools”, “Global Options”, “General”, change R version.

Likewise, if phenotools only works in the windows implementation of Rstudio/R (the way I understand it now), this is worth mentioning in the instructions. 

Best, Ida

**Comment by lauriejh** [comment]
Thanks Ida - I will check this and add an R version requirement to the package if necessary (I can't think immediately why 3.4 wouldn't work, so if it's an easy fix I will allow that to be the minimum) in the upcoming release.

Also think there is no reason it shouldn't work on the linux vms, but the install would be different - I will check and add instructions.

Please let me know as you encounter other issues - I will add you to the slack if that's ok.

**Comment by idaElken** [comment]
Sounds good. Part of the error message was:  "... need R 3.5.0 or newer". 

Let me know if you prefer feedback in slack or on github :-)

**Comment by espenhgn** [comment]
Can confirm Linux host + R 4.2.1 appears to be a no go on TSD/p697, using the p697-appn-norment01 and R/4.2.1-foss-2022a module:
![image](https://github.com/psychgen/phenotools/assets/2492641/114e1663-4f98-439a-afb8-3265597f66d0)

Also, I have a kind request, @lauriejh: As there appear to be phenotools versions >0.2.9 in circulation, would it be possible to make these codes publicly available here, as commits on the main branch (with corresponding git tag(s)) or feature branch(es)?

**Comment by espenhgn** [comment]
Yes, it appears to be a mix of issues related to OS; binary installation won't work obviously. It appears `devtools::install_local` works for installation on Linux in contrast to `install.packages()`,  here using a fresh copy of the GitHub files:
![image](https://github.com/psychgen/phenotools/assets/2492641/be20259c-fc2f-4665-8697-ee69dbd2774c)

I'll let you know if I encounter more issues on this OS (just starting....). 

Also thanks for providing an update on GitHub. As for usage, in our group would like to incorporate phenotools in Docker/Singularity software containers for usage in different projects/pipelines, and for this, we ideally need to pull sources from a public resource (such as GitHub).
