### ISSUE TITLE
KUHR - codes in 2006 & 2007 

### ISSUE THREAD

**Issue by E-Claire** [psychgen/phenotools#5]
Just had a random question about KUHR years available. My understanding was that KUHR includes data from 2006 onwards (based on the information in these websites https://www.helsedirektoratet.no/tema/statistikk-registre-og-rapporter/helsedata-og-helseregistre/kuhr, https://helsedata.no/no/forvaltere/helsedirektoratet/kontroll-og-utbetaling-av-helserefusjoner-kuhr/). However, for children with the ICPC-2 P06 codes (sleep disturbances) in KHUR the earliest year of first diagnosis was 2008. I went back an re-ran phenotools to see if had done something wrong and realised that the KUHR data is read in from year 2008 onwards. Therefore, I was wondering if there might be a simple explanation for the lack of KUHR data from 2006 and 2007 and if so whether you know the reason for this?

When I emailed you about this you pointed out that 2006 and 2007 may have been rolled into a single year together with 2008 as 2008 has a lot higher rate of cases.

Raising the issue here to be looked into.

**Comment by lauriejh** [comment]
Closing as not a phenotools-related issue - will email you @E-Claire
