### ISSUE TITLE
NPR data- needs MBRN data

### ISSUE THREAD

**Issue by KatharinaHaag** [psychgen/phenotools#6]
When trying to extract NPR diagnoses, I get an error saying that the MBRN file does not exist, with the suggested pathway leading to a file that is not on our server (see attached error message)
![phenotools_error message](https://github.com/psychgen/phenotools/assets/142216808/125e09af-4577-42df-a410-4c2d02d8d552)

**Comment by espenmei** [comment]
Could it be because tsd have changed the default path so it doesnt contain "data/" anymore?

**Comment by lauriejh** [comment]
curate_npr and curate_kuhr were not correctly inheriting user specified filepath overrides from curate_dataset. Resolved in 0.3.0.999
