### ISSUE TITLE
KUHR linkage file directory 

### ISSUE THREAD

**Issue by E-Claire** [psychgen/phenotools#7]
In p471, the path to the linkage file needs updating. Currently looks for the file in "//ess01/P471/data/durable/data/Linkage_files/" instead of "//ess01/P471/data/durable/data/Linkage_files/KUHR_link/". NB this was noticed using phenotools_0.3.0.

**Comment by lauriejh** [comment]
Defaults for both kuhr and npr updated in v0.3.0.9999
